<div id="mw-promo-banner" class="mw-banner">
    <div class="mw-container">
        <div class="mw-container__left">
            <span class="mw-banner__percent">43%</span>
        </div>
        <div class="mw-container__center">
            <p class="mw-banner__content">of site visitors go immediately to a search box and searchers are 2-3 times more likely to convert.</p>
            <i class="mw-banner__researcher">Based on the Forrester Research</i>
            <p class="mw-banner__content">Get 3x sales boost &mdash; improve onsite search today!</p>
        </div>
        <div class="mw-container__right">
            <p class="mw-banner__content"><a target="_blank" href="https://www.mageworx.com/magento-2-search-extension.html" class="mw-banner__link">Instant search suite</a></p>
            <p class="mw-banner__content">10% OFF!</p>
            <p class="mw-banner__code">Use code: <strong>10XSEARCH</strong></p>
            <p class="mw-banner__content"><a target="_blank" href="https://www.mageworx.com/magento-2-search-extension.html" class="mw-banner__button">Buy now</a></p>
        </div>
    </div>
</div>